### ISSUE TITLE
Disable simple thing

### ISSUE THREAD

**Issue by ErunBlizzard** [Dev7ex/MultiPerms#1]
Hello here

I would like to disable the base of minecraft for people who just joined my server, they would have perm of "default" as the plugin give when you join for the first time but i would like to remove the posibility of placing or breaking block and open any kind of chest (barrel,ender chest,shulker box,hopper,minecart with chest or hopper,furnace,etc...)

It the first time that i work with a plugin like this and i don't see anything anywhere that could help me doing that so i hope you could help me.

i need the player to stay in survival for this.

i hope all i writed here is understandable if not im sorry english isn't my first language.
On this i hope you have a plesant day.

**Comment by Dev7ex** [comment]
Hey, I saw your suggestion and I think this will be implemented as an addon for MultiPerms as soon as this idea is implemented I'll get back to you.

**Comment by Dev7ex** [comment]
Has been added in version 1.0.1
